In [6]:
import pandas as pd
pandas.__version__

'2.1.4'

In [2]:
"A"*3

'AAA'

In [4]:
"ABC"[0:2]

'AB'

In [79]:
stock = pd.read_excel("Data/2024-03-22_국내주식.xlsx")

In [9]:
stock.describe()

,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,고가,저가,...,주당순이익,보통주배당금,매출액증가율,영업이익증가율,외국인비율,PER,ROE,ROA,PBR,유보율
count,3.881000e+03,3881.000000,3881.000000,3881.000000,3.881000e+03,3.881000e+03,3.881000e+03,3.881000e+03,3.881000e+03,3.881000e+03,...,2623.000000,1790.000000,2363.000000,2.411000e+03,3881.000000,2619.000000,2410.000000,2410.000000,2642.000000,2.532000e+03
mean,2.178075e+04,278.779181,0.251013,697.011337,4.998875e+05,6.201453e+03,6.214262e+05,2.167128e+04,2.197687e+04,2.141305e+04,...,1112.698818,414.364246,36.381413,5.136749e+05,4.167380,12.548217,-2.297975,-0.886631,2.011525,5.386672e+03
std,5.126904e+04,1065.303508,2.759883,1301.617148,3.602333e+06,4.455757e+04,5.299499e+06,5.121634e+04,5.188317e+04,5.076090e+04,...,8428.714583,1167.483392,483.331108,2.522108e+07,9.364766,431.175365,69.399240,17.570867,5.188829,1.121474e+05
min,7.400000e+01,0.000000,-30.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,-104950.000000,0.000000,-99.150000,-1.615801e+04,0.000000,-7225.000000,-1860.170000,-476.450000,-102.000000,-7.025400e+03
25%,3.835000e+03,15.000000,-0.520000,0.000000,5.268000e+03,4.500000e+01,7.851000e+03,3.745000e+03,3.805000e+03,3.675000e+03,...,-190.000000,0.000000,-6.425000,-5.571000e+01,0.000000,-5.190000,-4.937500,-2.832500,0.560000,3.467250e+02
50%,9.500000e+03,55.000000,0.030000,500.000000,4.259000e+04,2.750000e+02,5.205700e+04,9.415000e+03,9.540000e+03,9.310000e+03,...,136.000000,95.000000,7.450000,-2.190000e+00,0.800000,6.660000,3.930000,2.090000,1.050000,9.866000e+02
75%,1.758000e+04,185.000000,0.880000,500.000000,1.960360e+05,1.610000e+03,2.155280e+05,1.746500e+04,1.773000e+04,1.728000e+04,...,882.000000,300.000000,23.415000,5.176000e+01,3.400000,19.755000,10.067500,5.890000,2.030000,2.144625e+03
max,1.030660e+06,28800.000000,29.990000,5000.000000,1.822181e+08,2.095870e+06,2.312783e+08,1.030660e+06,1.030665e+06,1.030660e+06,...,309200.000000,18000.000000,15952.760000,1.238404e+09,83.170000,19100.000000,997.790000,59.510000,72.980000,4.871522e+06

In [80]:
stock.info() # 영업이익증가율, 매출액증가율, 매출액, 영업이익, 부채총계/자산총계

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3881 entries, 0 to 3880
Data columns (total 33 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   종목명      3881 non-null   object
 1   현재가      3881 non-null   int64
 2   전일비      3881 non-null   int64
 3   등락률      3881 non-null   float64
 4   액면가      3881 non-null   int64
 5   거래량      3881 non-null   int64
 6   거래대금     3881 non-null   int64
 7   전일거래량    3881 non-null   int64
 8   시가       3881 non-null   int64
 9   고가       3881 non-null   int64
 10  저가       3881 non-null   int64
 11  매수호가     3881 non-null   int64
 12  매도호가     3881 non-null   int64
 13  매수총잔량    3881 non-null   int64
 14  매도총잔량    3881 non-null   int64
 15  상장주식수    3881 non-null   int64
 16  시가총액     3881 non-null   int64
 17  매출액      2471 non-null   float64
 18  자산총계     2532 non-null   float64
 19  부채총계     2532 non-null   float64
 20  영업이익     2532 non-null   float64
 21  당기순이익    2532 non-null   float64
 22  주당순이익    2623 non-null   float64
 23  보통주배당금   1790 non-null   float64
 24  매출액증가율   2363 non-null   float64
 25  영업이익증가율  2411 non-null   float64
 26  외국인비율    3881 non-null   float64
 27  PER      2619 non-null   float64
 28  ROE      2410 non-null   float64
 29  ROA      2410 non-null   float64
 30  PBR      2642 non-null   float64
 31  유보율      2532 non-null   float64
 32  소속       3881 non-null   object
dtypes: float64(16), int64(15), object(2)
memory usage: 1000.7+ KB

In [18]:
stock[(stock["PER"]<=1) & (stock["PBR"] <= 1) & (stock["ROE"] > 10)]
stock.sort_values("시가총액", ascending=0)

,종목명,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,고가,...,보통주배당금,매출액증가율,영업이익증가율,외국인비율,PER,ROE,ROA,PBR,유보율,소속
0,삼성전자,78900,400,-0.50,100,26614741,2095870,44569799,79600,79900,...,1444.0,-14.33,-84.86,54.85,37.02,4.15,3.43,1.52,39114.3,KOSPI
1,SK하이닉스,169800,200,-0.12,5000,5346307,912457,9205769,169000,173900,...,1200.0,-26.57,-213.52,54.39,-13.57,-15.61,-8.95,2.18,1397.1,KOSPI
2,LG에너지솔루션,413500,0,0.00,500,136037,56177,154423,410500,415500,...,NaN,31.83,78.23,5.01,78.21,6.36,3.91,4.79,16691.6,KOSPI
3,삼성바이오로직스,840000,17000,-1.98,2500,51862,43772,76873,851000,856000,...,NaN,23.10,13.22,11.95,69.70,9.12,5.26,6.08,5432.6,KOSPI
4,삼성전자우,66700,900,1.37,100,3580668,237602,3545573,67000,67100,...,NaN,NaN,NaN,74.96,31.30,NaN,NaN,1.28,NaN,KOSPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2157,KBSTAR 미국장기국채선물인버스(H),10545,15,-0.14,0,4,0,163,10565,10565,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,KOSPI
2159,KBSTAR 200생활소비재,6025,30,0.50,0,186,1,4481,6000,6060,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,KOSPI
2160,KBSTAR Fn K-뉴딜디지털플러스,8625,35,0.41,0,11,0,27,8600,8625,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,KOSPI
2158,KBSTAR 200커뮤니케이션서비스,11210,30,0.27,0,28,0,11,11225,11265,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,KOSPI
2161,KBSTAR 200산업재,12610,20,0.16,0,9,0,16,12680,12705,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,KOSPI

In [25]:
# 이주영: PBR, PER, ROE별 가중치 필요하지 않나
# 김정수: PBR, PER이 산업군별로 상이 / 업종이 없음(자료가 부족)
# 기여은: 영업이익 순으로 산정필요
# 최진호: 자료가 부족하기에 배당률이 높거나 하는 등 특정 기준 하에서 진행하는 것이 필요하다고 봄. 미래 성장가능성에 투자하는 것이기에 
# 주식: 거래량이 높을수록 좋다. ROE가 높을수록 좋다(한 주당 얼마나 가치를 지니는 지), 매출액 증가추이, 영업이익 증가추이,
#      매출액 대비 영업이익, 유보율(주주배당하지않고, 유보하여 유보만큼 재투자)
# 분석대상: 거래량, 영업이익/매출액, ROE,매출액증가율, 영업이익증가율, 유보율

def remove_out(dataframe, remove_col):
    dff = dataframe
    for k in remove_col:
        level_1q = dff[k].quantile(0.25)
        level_3q = dff[k].quantile(0.75)
        IQR = level_3q - level_1q
        rev_range = 3  # 제거 범위 조절 변수
        dff = dff[(dff[k] <= level_3q + (rev_range * IQR)) & (dff[k] >= level_1q - (rev_range * IQR))]
        dff = dff.reset_index(drop=True)
    return dff

Good_PBR = stock["PBR"] <= 1
Good_PER = stock["PER"] <= 1
Good_ROE = stock["ROE"] >= 10
Good = stock[Good_PBR & Good_PER & Good_ROE]

In [137]:
# 각 항목별 가중치를 두어, 필요한 데이터를 산정 후 재계산 
# 가중치항목: 영업이익증가율, 매출액증가율, 영업대비매출액(영업이익률/매출액), ROE, 거래량
# 이상치 제거함수(detect_outliers)를 두고 이상치 내용들은 제거함

import pandas as pd
stock = pd.read_excel("Data/2024-03-22_국내주식.xlsx")

def detect_outliers(df, columns):
    q1 = df[columns].quantile(0.25)
    q3 = df[columns].quantile(0.75)
    IQR = q3 - q1

    boundary = 1.5 * IQR

    index1 = df[df[columns] > q3 + boundary].index
    index2 = df[df[columns] < q1 - boundary].index

    df[columns] = df[columns].drop(index1)
    df[columns] = df[columns].drop(index2)

    return df

realStock = detect_outliers(stock, "PBR")
realStock = detect_outliers(realStock, "PER")
realStock = detect_outliers(realStock, "ROE")
realStock = detect_outliers(realStock, "ROA")
realStock = detect_outliers(realStock, "유보율")
realStock = detect_outliers(realStock, "외국인비율")
realStock = detect_outliers(realStock, "거래량")
realStock = detect_outliers(realStock, "거래대금")
realStock = detect_outliers(realStock, "시가총액")

realStock['영업대비매출액'] = realStock['영업이익']/realStock['매출액']
realStock['부채비율'] = realStock['부채총계'] / realStock['자산총계']

realStock = detect_outliers(realStock, "영업대비매출액")
realStock = detect_outliers(realStock, "부채비율")

realStock['R영업이익증가율'] = realStock['영업이익증가율'].rank(method='average', ascending = 1)
realStock['R매출액증가율'] = realStock['매출액증가율'].rank(method='average', ascending = 1)
realStock['R영업대비매출액'] = realStock['영업대비매출액'].rank(method='average', ascending = 1)
realStock['R부채비율'] = realStock['부채비율'].rank(method='average', ascending=0)
realStock['R_ROE'] = realStock['ROE'].rank(method='average', ascending = 1)
realStock['R거래량'] = realStock['거래량'].rank(method='average', ascending = 1)

realStock['score'] = realStock['R영업이익증가율'] * 0.25 + realStock['R매출액증가율'] * 0.2 + realStock['R영업대비매출액'] * 0.3 + realStock['R_ROE'] * 0.15 +   realStock['R거래량'] * 0.1
dropedStock = realStock.dropna()

dropedStock.sort_values('score', ascending=0)

,종목명,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,고가,...,소속,영업대비매출액,부채비율,R영업이익증가율,R매출액증가율,R영업대비매출액,R부채비율,R_ROE,R거래량,score
2750,케이엔제이,18850,320,1.73,500,198498.0,3688.0,345294,18300,19150,...,KOSDAQ,0.213483,0.502313,2227.0,1979.0,2020.0,853.0,1955.0,2916.0,2143.400
2749,케이에스피,3745,5,-0.13,500,268681.0,1022.0,329109,3770,3945,...,KOSDAQ,0.144608,0.386454,2250.0,1874.5,1847.0,1298.0,2071.0,3131.0,2115.250
2857,이루다,6100,30,0.49,500,117322.0,707.0,72910,6110,6110,...,KOSDAQ,0.179266,0.435669,2045.0,2143.0,1953.0,1103.0,1949.0,2589.0,2077.000
3325,원바이오젠,1772,27,-1.50,100,116527.0,207.0,164381,1829,1829,...,KOSDAQ,0.194757,0.311054,2161.0,2146.0,1988.0,1574.0,1641.5,2582.0,2070.275
2530,LS마린솔루션,9430,50,0.53,1000,73864.0,700.0,56140,9410,9590,...,KOSDAQ,0.185028,0.164281,2280.0,2210.0,1972.0,2109.0,1532.0,2307.0,2064.100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3341,오텍,4155,15,0.36,500,11699.0,48.0,7100,4110,4175,...,KOSDAQ,-0.018735,0.767457,105.0,816.5,356.0,151.0,6.0,1245.0,421.750
3091,오르비텍,3320,5,-0.15,500,193059.0,638.0,192101,3325,3325,...,KOSDAQ,-0.199324,0.516047,195.0,192.0,3.0,792.0,30.0,2904.0,382.950
3355,남화토건,5290,50,0.95,500,27685.0,148.0,19846,5350,5440,...,KOSDAQ,-0.061281,0.136535,211.0,241.0,219.0,2204.0,279.0,1672.0,375.700
3193,NPX,8040,0,0.00,500,0.0,0.0,0,0,0,...,KOSDAQ,-0.040000,0.080769,342.0,68.0,272.5,2417.0,571.5,87.5,275.325
3310,CNH,1790,4,-0.22,2500,8241.0,15.0,6033,1794,1799,...,KOSDAQ,-0.178176,0.793895,35.0,263.0,20.0,119.0,152.5,1106.0,200.825

In [122]:
realStock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3881 entries, 0 to 3880
Data columns (total 42 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   종목명       3881 non-null   object
 1   현재가       3881 non-null   int64
 2   전일비       3881 non-null   int64
 3   등락률       3881 non-null   float64
 4   액면가       3881 non-null   int64
 5   거래량       3370 non-null   float64
 6   거래대금      3261 non-null   float64
 7   전일거래량     3881 non-null   int64
 8   시가        3881 non-null   int64
 9   고가        3881 non-null   int64
 10  저가        3881 non-null   int64
 11  매수호가      3881 non-null   int64
 12  매도호가      3881 non-null   int64
 13  매수총잔량     3881 non-null   int64
 14  매도총잔량     3881 non-null   int64
 15  상장주식수     3881 non-null   int64
 16  시가총액      3881 non-null   int64
 17  매출액       2471 non-null   float64
 18  자산총계      2532 non-null   float64
 19  부채총계      2532 non-null   float64
 20  영업이익      2532 non-null   float64
 21  당기순이익     2532 non-null   float64
 22  주당순이익     2623 non-null   float64
 23  보통주배당금    1790 non-null   float64
 24  매출액증가율    2363 non-null   float64
 25  영업이익증가율   2411 non-null   float64
 26  외국인비율     3881 non-null   float64
 27  PER       2196 non-null   float64
 28  ROE       2072 non-null   float64
 29  ROA       2410 non-null   float64
 30  PBR       2389 non-null   float64
 31  유보율       2532 non-null   float64
 32  소속        3881 non-null   object
 33  영업대비매출액   2069 non-null   float64
 34  부채비율      2522 non-null   float64
 35  R영업이익증가율  2411 non-null   float64
 36  R매출액증가율   2363 non-null   float64
 37  R영업대비매출액  2069 non-null   float64
 38  R부채비율     2522 non-null   float64
 39  R_ROE     2072 non-null   float64
 40  R거래량      3370 non-null   float64
 41  score     1554 non-null   float64
dtypes: float64(27), int64(13), object(2)
memory usage: 1.2+ MB

In [84]:
# df['sum']=df.iloc[:, 2:].sum(axis=1)
# average: 3등이 2명이면, 둘다 3.5등으로 처리하고 다음 등수를 5등
# df['순위']=df['sum'].rank(method='average',ascending=0)
# df.sort_values('sum', ascending=0)

#영업이익증가율, 매출액증가율, 영업이익률/매출액(# 영업이익증가율, 매출액증가율, 매출액, 영업이익), ROE, 거래량, 부채비율(부채총계/자산총계)

realStock['R영업이익증가율'] = realStock['영업이익증가율'].rank(method='average')
realStock['R매출액증가율'] = realStock['매출액증가율'].rank(method='average')
realStock['R영업대비매출액'] = realStock['영업대비매출액'].rank(method='average')
realStock['R부채비율'] = realStock['부채비율'].rank(method='average')
realStock['R_ROE'] = realStock['ROE'].rank(method='average')
realStock['R거래량'] = realStock['거래량'].rank(method='average')
realStock['R_ROE'] = realStock['ROE'].rank(method='average')
realStock['score'] = realStock['R영업이익증가율'] + realStock['R매출액증가율'] + realStock['R영업대비매출액'] + realStock['R_ROE'] +   realStock['R거래량'] 
dropedStock = realStock.dropna()
dropedStock.sort_values('부채비율', ascending=0)

,종목명,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,고가,...,소속,영업대비매출액,부채비율,R영업이익증가율,R매출액증가율,R영업대비매출액,R부채비율,R_ROE,R거래량,score
118,한화생명,3195,55,-1.69,5000,1838049,5924,2354274,3260,3285,...,KOSPI,0.021207,0.950289,668.0,1791.0,986.0,2510.0,1353.0,3708.0,8506.0
230,동양생명,6340,20,0.32,5000,194702,1230,463793,6320,6400,...,KOSPI,0.012637,0.948971,568.0,2197.0,860.0,2508.0,716.0,2910.0,7251.0
267,아시아나항공,11180,40,0.36,5000,128226,1432,218718,11140,11250,...,KOSPI,0.096476,0.946816,2343.0,2089.0,1912.0,2506.0,1799.0,2651.0,10794.0
32,우리금융지주,15200,90,-0.59,5000,2055848,31416,3738348,15140,15450,...,KOSPI,0.083337,0.932937,951.0,778.5,1818.0,2503.0,1266.0,3726.0,8539.5
28,기업은행,15280,120,0.79,5000,2542295,39057,2247837,15280,15520,...,KOSPI,0.137085,0.932611,1491.0,2183.0,2112.0,2502.0,1420.0,3745.0,10951.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,LX홀딩스,7010,10,0.14,1000,90845,635,59823,7020,7020,...,KOSPI,0.619814,0.021019,621.0,52.0,2452.0,7.0,911.5,2441.0,6477.5
2497,인트론바이오,7700,0,0.00,500,252315,1943,258224,7730,7860,...,KOSDAQ,-0.343750,0.019270,330.0,119.0,202.0,6.0,128.5,3087.0,3866.5
990,써니전자,2150,5,0.23,500,162776,348,337328,2150,2160,...,KOSPI,0.070312,0.018182,675.0,165.0,1687.0,5.0,935.5,2801.0,6263.5
3655,씨엑스아이,120,1,0.84,0,1166084,139,1543145,119,120,...,KOSDAQ,0.099162,0.008413,1441.5,133.0,1932.0,2.0,592.0,3637.0,7735.5
982,NH프라임리츠,4285,0,0.00,500,48270,206,34840,4290,4305,...,KOSPI,0.876712,0.002712,1942.0,2260.0,2459.0,1.0,1555.5,2009.0,10225.5