In [1]:
import pandas as pd
import koreanize_matplotlib
import seaborn as sns
from sklearn.model_selection import train_test_split # sklearn : 75:25 비율로 나누길 권장 (Google : 8:2 비율 권장)
import numpy as np
import koreanize_matplotlib

In [3]:
# 데이터 크롤리
from bs4 import BeautifulSoup # Python으로 HTML을 다루는 기능
import requests # 페이지 요청
import pandas as pd # 엑셀화
import time
import random

In [27]:
# 최근의 로또 페이지 URL 호출하여, bs4로 변환
url = requests.get("https://search.daum.net/search?nil_suggest=btn&w=tot&DA=SBC&q=%EB%A1%9C%EB%98%90")
html = BeautifulSoup(url.text, 'html.parser')

In [42]:
# 현재 회차횟수(current)
current = int(
    html.find('span', 
              attrs = {'class': "f_red"})
    .text[:-1])

#first_num = int(html.find('span', attrs = {'class': 'ball bg_ball1'}).text)

# 전체 번호 가져오기
numbers = html.find("div", attrs = {'class': 'lottonum'}).find_all('span')
del numbers[-3:-1]
numbers

# box 리스트 내 각 번호별 리스트로 분배
box = []
for i in numbers:
    print(i.text)
    box.append(int(i.text))
box

7
12
23
32
34
36
8

[7, 12, 23, 32, 34, 36, 8]

In [43]:
# 20회 정도 로또 정보 가져오기
total = []
for n in range(1, 21):
    url = requests.get(f"https://search.daum.net/search?w=tot&rtmaxcoll=LOT&DA=LOT&q={n}%ED%9A%8C%20%EB%A1%9C%EB%98%90%EB%8B%B9%EC%B2%A8%EB%B2%88%ED%98%B8")
    html = BeautifulSoup(url.text, 'html.parser')
    time.sleep(random.random() + 1) # 0~1 사이의 랜덤한값 +1 = 1.x초
    
    # 전체 번호 가져오기
    numbers = html.find("div", attrs = {'class': 'lottonum'}).find_all('span')
    del numbers[-3:-1]
    
    # 각 번째 번호마다 box에 넣기
    box = []
    for i in numbers:
        box.append(int(i.text))
    # 전체 번호는 total에 리스트로 넣기
    total. append(box)
        
    print(f"{n}회차 로또 저장완료 : {box}")

1회차 로또 저장완료 : [10, 23, 29, 33, 37, 40, 16]
2회차 로또 저장완료 : [9, 13, 21, 25, 32, 42, 2]
3회차 로또 저장완료 : [11, 16, 19, 21, 27, 31, 30]
4회차 로또 저장완료 : [14, 27, 30, 31, 40, 42, 2]
5회차 로또 저장완료 : [16, 24, 29, 40, 41, 42, 3]
6회차 로또 저장완료 : [14, 15, 26, 27, 40, 42, 34]
7회차 로또 저장완료 : [2, 9, 16, 25, 26, 40, 42]
8회차 로또 저장완료 : [8, 19, 25, 34, 37, 39, 9]
9회차 로또 저장완료 : [2, 4, 16, 17, 36, 39, 14]
10회차 로또 저장완료 : [9, 25, 30, 33, 41, 44, 6]
11회차 로또 저장완료 : [1, 7, 36, 37, 41, 42, 14]
12회차 로또 저장완료 : [2, 11, 21, 25, 39, 45, 44]
13회차 로또 저장완료 : [22, 23, 25, 37, 38, 42, 26]
14회차 로또 저장완료 : [2, 6, 12, 31, 33, 40, 15]
15회차 로또 저장완료 : [3, 4, 16, 30, 31, 37, 13]
16회차 로또 저장완료 : [6, 7, 24, 37, 38, 40, 33]
17회차 로또 저장완료 : [3, 4, 9, 17, 32, 37, 1]
18회차 로또 저장완료 : [3, 12, 13, 19, 32, 35, 29]
19회차 로또 저장완료 : [6, 30, 38, 39, 40, 43, 26]
20회차 로또 저장완료 : [10, 14, 18, 20, 23, 30, 41]

In [46]:
lotto = pd.DataFrame(total, columns=['1번째','2번째','3번째','4번째','5번째','6번째','보너스'])
# lotto.to_excel("lotto.xlsx",index=False)

    1번째  2번째  3번째  4번째  5번째  6번째  보너스
0    10   23   29   33   37   40   16
1     9   13   21   25   32   42    2
2    11   16   19   21   27   31   30
3    14   27   30   31   40   42    2
4    16   24   29   40   41   42    3
5    14   15   26   27   40   42   34
6     2    9   16   25   26   40   42
7     8   19   25   34   37   39    9
8     2    4   16   17   36   39   14
9     9   25   30   33   41   44    6
10    1    7   36   37   41   42   14
11    2   11   21   25   39   45   44
12   22   23   25   37   38   42   26
13    2    6   12   31   33   40   15
14    3    4   16   30   31   37   13
15    6    7   24   37   38   40   33
16    3    4    9   17   32   37    1
17    3   12   13   19   32   35   29
18    6   30   38   39   40   43   26
19   10   14   18   20   23   30   41

In [49]:
url = requests.get("https://search.daum.net/search?w=tot&DA=JIM&rtmaxcoll=JIM&&q=%EC%97%B0%EA%B8%88%EB%B3%B5%EA%B6%8C%20520%201%ED%9A%8C%EC%B0%A8")
html = BeautifulSoup(url.text, 'html.parser')

html.find("div", {'class':'inner'}).find_all('span')

[<span class="num">5</span>,
 <span class="num">3</span>,
 <span class="num">0</span>,
 <span class="num">5</span>,
 <span class="num">6</span>,
 <span class="num">2</span>]

In [59]:
##########################
########### 연금복권 가져오기
##########################

from bs4 import BeautifulSoup as bs# Python으로 HTML을 다루는 기능
import requests # 페이지 요청
import pandas as pd # 엑셀화
import time
import random

# 20회 정도 로또 정보 가져오기
total = []
for n in range(1, 2):
    url = requests.get(f"https://search.daum.net/search?w=tot&DA=JIM&rtmaxcoll=JIM&&q=%EC%97%B0%EA%B8%88%EB%B3%B5%EA%B6%8C%20520%20{n}%ED%9A%8C%EC%B0%A8")
    html = BeautifulSoup(url.text, 'html.parser')
    time.sleep(random.random() + 1) # 0~1 사이의 랜덤한값 +1 = 1.x초
    
    # (선생님풀이법) 전체 번호 가져오기
    numbers = html.find("tr", class_ = 'fst').text.split()[5:]
    
    # 각 번째 번호마다 box에 넣기
    box = []
    for i in numbers:
        box.append(i)
    # 전체 번호는 total에 리스트로 넣기
    total. append(box)
        
    print(f"{n}회차 연금복권 저장완료 : {box}")

pension_lottery = pd.DataFrame(total, columns=['조','1번째','2번째','3번째','4번째','5번째','6번째'])
#pension_lottery.to_excel("pension_lottery.xlsx",index=False)

1회차 연금복권 저장완료 : ['5조', '5', '3', '0', '5', '6', '2']

In [133]:
###########################
# 네이버 주식 정보 가져오기(코스피)
###########################
import warnings
warnings.filterwarnings('ignore')

url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?sosok=0&page=1") # 우선 한번 코스피(sosok=0)의 페이지를 한번 불러봄
html = BeautifulSoup(url.text)
kospi_page = int(html.find("td", class_ = "pgRR").find("a")['href'][-2:]) # 맨 뒷페이지의 페이지 번호는?

kospi_box = []
for page in range(1, kospi_page+1):
    url = requests.get(f"https://finance.naver.com/sise/sise_market_sum.naver?sosok=0&page={page}")
    html = BeautifulSoup(url.text)
    time.sleep(random.random() + 1) # 0~1 사이의 랜덤한값 +1 = 1.x초
    
    table = html.find('table', class_ = "type_2") # HTML 내 Table 정보를 가져옴
    table = pd.read_html(str(table))[0] # 이 테이블을 바로 pd로 전환하여 표현
    table = table.dropna(subset="종목명") # 이 중 종목명이 NA인 경우 제외(drop)
    
    del table['N']
    del table['토론실']
    #table = table.iloc[1:-3]
    
    kospi_box.append(table)
    print(f"코스피 {page}페이지 수집 완료")
    
kospi = pd.concat(kospi_box, ignore_index=True)
#kospi.to_excel("kospi.xlsx", index=False)

코스피 1페이지 수집 완료
코스피 2페이지 수집 완료
코스피 3페이지 수집 완료
코스피 4페이지 수집 완료
코스피 5페이지 수집 완료
코스피 6페이지 수집 완료
코스피 7페이지 수집 완료
코스피 8페이지 수집 완료
코스피 9페이지 수집 완료
코스피 10페이지 수집 완료
코스피 11페이지 수집 완료
코스피 12페이지 수집 완료
코스피 13페이지 수집 완료
코스피 14페이지 수집 완료
코스피 15페이지 수집 완료
코스피 16페이지 수집 완료
코스피 17페이지 수집 완료
코스피 18페이지 수집 완료
코스피 19페이지 수집 완료
코스피 20페이지 수집 완료
코스피 21페이지 수집 완료
코스피 22페이지 수집 완료
코스피 23페이지 수집 완료
코스피 24페이지 수집 완료
코스피 25페이지 수집 완료
코스피 26페이지 수집 완료
코스피 27페이지 수집 완료
코스피 28페이지 수집 완료
코스피 29페이지 수집 완료
코스피 30페이지 수집 완료
코스피 31페이지 수집 완료
코스피 32페이지 수집 완료
코스피 33페이지 수집 완료
코스피 34페이지 수집 완료
코스피 35페이지 수집 완료
코스피 36페이지 수집 완료
코스피 37페이지 수집 완료
코스피 38페이지 수집 완료
코스피 39페이지 수집 완료
코스피 40페이지 수집 완료
코스피 41페이지 수집 완료
코스피 42페이지 수집 완료
코스피 43페이지 수집 완료
코스피 44페이지 수집 완료

In [134]:
###########################
# 네이버 주식 정보 가져오기(코스닥)
###########################
import warnings
warnings.filterwarnings('ignore')

url = requests.get("https://finance.naver.com/sise/sise_market_sum.naver?sosok=1&page=1") # 우선 한번 코스닥(sosok=1)의 페이지를 한번 불러봄
html = BeautifulSoup(url.text)
kosdaq_page = int(html.find("td", class_ = "pgRR").find("a")['href'][-2:]) # 맨 뒷페이지의 페이지 번호는?

kosdaq_box = []
for page in range(1, kosdaq_page+1):
    url = requests.get(f"https://finance.naver.com/sise/sise_market_sum.naver?sosok=1&page={page}")
    html = BeautifulSoup(url.text)
    time.sleep(random.random() + 1) # 0~1 사이의 랜덤한값 +1 = 1.x초
    
    table = html.find('table', class_ = "type_2") # HTML 내 Table 정보를 가져옴
    table = pd.read_html(str(table))[0] # 이 테이블을 바로 pd로 전환하여 표현
    table = table.dropna(subset="종목명") # 이 중 종목명이 NA인 경우 제외(drop)
    
    del table['N']
    del table['토론실']
    #table = table.iloc[1:-3]
    
    kosdaq_box.append(table)
    print(f"코스닥 {page}페이지 수집 완료")
    
kosdaq = pd.concat(kosdaq_box, ignore_index=True)
kosdaq.to_excel("kosdaq.xlsx", index=False)

코스닥 1페이지 수집 완료
코스닥 2페이지 수집 완료
코스닥 3페이지 수집 완료
코스닥 4페이지 수집 완료
코스닥 5페이지 수집 완료
코스닥 6페이지 수집 완료
코스닥 7페이지 수집 완료
코스닥 8페이지 수집 완료
코스닥 9페이지 수집 완료
코스닥 10페이지 수집 완료
코스닥 11페이지 수집 완료
코스닥 12페이지 수집 완료
코스닥 13페이지 수집 완료
코스닥 14페이지 수집 완료
코스닥 15페이지 수집 완료
코스닥 16페이지 수집 완료
코스닥 17페이지 수집 완료
코스닥 18페이지 수집 완료
코스닥 19페이지 수집 완료
코스닥 20페이지 수집 완료
코스닥 21페이지 수집 완료
코스닥 22페이지 수집 완료
코스닥 23페이지 수집 완료
코스닥 24페이지 수집 완료
코스닥 25페이지 수집 완료
코스닥 26페이지 수집 완료
코스닥 27페이지 수집 완료
코스닥 28페이지 수집 완료
코스닥 29페이지 수집 완료
코스닥 30페이지 수집 완료
코스닥 31페이지 수집 완료
코스닥 32페이지 수집 완료
코스닥 33페이지 수집 완료
코스닥 34페이지 수집 완료
코스닥 35페이지 수집 완료

In [138]:
#####################
# 코스피/코스닥 소속 구분하고
# 코스피 + 코스닥(한국시장)
#####################
kospi['소속'] = '코스피'
kosdaq['소속'] = '코스닥'

korea_market = pd.concat([kospi, kosdaq], ignore_index=True)
korea_market.to_excel("korea_market.xlsx", index=False)
korea_market

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,소속
0,삼성전자,77600.0,2000.0,-2.51%,100.0,4632551.0,5969783.0,55.99,31198311.0,36.41,4.15,코스피
1,SK하이닉스,173300.0,9000.0,-4.94%,5000.0,1261628.0,728002.0,54.67,7396935.0,-13.85,-15.61,코스피
2,LG에너지솔루션,367000.0,10000.0,-2.65%,500.0,858780.0,234000.0,4.86,142680.0,69.42,6.36,코스피
3,삼성바이오로직스,781000.0,9000.0,-1.14%,2500.0,555869.0,71174.0,11.99,55598.0,64.81,9.12,코스피
4,삼성전자우,65200.0,1100.0,-1.66%,100.0,536522.0,822887.0,75.75,1488373.0,30.60,NaN,코스피
...,...,...,...,...,...,...,...,...,...,...,...,...
3889,THE MIDONG,366.0,0.0,0.00%,500.0,77.0,21096.0,6.84,0.0,-1.88,-19.95,코스닥
3890,하나32호스팩,2275.0,5.0,+0.22%,100.0,73.0,3200.0,2.60,57648.0,NaN,NaN,코스닥
3891,엔에이치스팩25호,2310.0,20.0,+0.87%,100.0,70.0,3020.0,0.17,11279.0,45.29,2.73,코스닥
3892,소프트센우,9800.0,200.0,-2.00%,200.0,35.0,357.0,0.21,291.0,-86.73,NaN,코스닥
3893,대호특수강우,8000.0,150.0,+1.91%,5000.0,34.0,424.0,0.28,421.0,-21.62,NaN,코스닥

In [149]:
# 일별 삼성전자 종가 가져오기
from bs4 import BeautifulSoup as bs
import requests

# User-Agent가 Python인 경우, 서버에서 차단하고, 일반 브라우저일때만, 회신하기에 User-Agent 헤더를 수동으로 조작변경
headers = {"User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.46"}
url = requests.get("https://finance.naver.com/item/sise_day.naver?code=005930&page=1", headers=headers)
html = bs(url.text)
lastpage = int(html.find("td", class_ = "pgRR").find("a")['href'][-3:]) # 맨 뒷페이지의 페이지 번호는?

table = html.find("table", class_ = "type2")
table = pd.read_html(str(table))[0]
table = table.dropna(subset="종가")

698

In [169]:
#############
# 매크로(셀레늄) 이용
# 크롬창을 직접열게하고, 클릭, 타이핑, 정보 수집
#############

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome()

driver.get("https://www.naver.com")
time.sleep(5)

search_input = driver.find_element(By.CSS_SELECTOR, "input.search_input") # input 태그의 {class: "search_input"} 찾기
search_input.send_keys("시난은행") # 검색바에 신한은행을 입력
search_input.send_keys(Keys.RETURN) # 검색바에 엔터를 입력

In [170]:
#########
# 인터파크 티켓 사이트 들어가서, 광고팝업 '닫기' 클릭
#########

driver = webdriver.Chrome()
driver.get("https://tickets.interpark.com/goods/24001487")
time.sleep(5)

element = driver.find_element(By.CSS_SELECTOR, "button.popupCloseBtn.is-bottomBtn")
element.click()
time.sleep(2)

In [179]:
# 관람후기 DOM을 찾아서 클릭
nav = driver.find_element(By.CSS_SELECTOR, "ul.navList")
navs = nav.find_elements(By.CSS_SELECTOR, 'li')

for i in navs:
    print(i.text)
    if "관람후기" in i.text:
        i.click()

공연정보
캐스팅정보
판매정보
관람후기999+
기대평140

In [198]:
# 관람후기 카테고리 요소 선택 
review_list = driver.find_element(By.CSS_SELECTOR, "ul.bbsList.reviewList")

# 리뷰 제목 수집
review_titles = [title.text for title in review_list.find_elements(By.CSS_SELECTOR, "strong.bbsTitleText")]

# 리뷰 내용 수집
review_contents = [content.text for content in review_list.find_elements(By.CSS_SELECTOR, "p.bbsText")]

# Pandas 데이터프레임으로 결과 정리
reviews_df = pd.DataFrame({
    "리뷰제목": review_titles,
    "리뷰내용": review_contents
})

# 결과 출력
reviews_df

                    리뷰제목                                               리뷰내용
0          책을 읽게 만드는 뮤지컬  브론테를 보고 나오면 브론테 자매들에 대해 크게 관심을 갖게 됩니다. 부끄럽지만 독...
1              최고의 공연이에요                                          최고의 공연이에요
2              최고의 공연이에요                                          최고의 공연이에요
3              최고의 공연이에요                                          최고의 공연이에요
4              최고의 공연이에요                                          최고의 공연이에요
5                     최고                                          최고의 공연이에요
6       재아 샬럿 너무 좋아요. :)                                 오늘 앤 무력행사 어마무시했어요.
7                 최고였어요!       처음본 뮤지컬인데 정말 재밌고 감동받으면서 봤어요!\n최고였어요 또 보러갈겁니다
8                    ♡♡♡           샬럿 에밀리 앤ㅠㅠ 자매 조합마다 맛이 달라지는 여러 번 봐야 하는 작품
9                  브론테!!                                   끝나기 전에 꼭 봐야 하는 극
10         눈이 여섯개면 좋겠는 극                  샬럿도 에밀리도 앤도 봐야 하는데 눈이 따라가지 못해 슬퍼요
11  브론테라는 이름을 사랑하게 될 거예요                                 사랑하게 됐으니 끝나지 말아요ㅠㅠ
12                벌써 페어막  시작한지 얼마 안 된 거 같은데 벌써 페어막이 나오는 게 슬프네요ㅠㅠ 더 부지런히 볼 걸
13                  최고에요                                이공연봤어 이공연봤어 모두가 열광해
14                   좋아요                                            또보고싶습니다

In [53]:
########
# (참고) ChatGPT4 가 만들어준 로또 수집기
#######

import requests
from bs4 import BeautifulSoup

# Daum 로또 페이지 URL
url = 'https://search.daum.net/search?nil_suggest=btn&w=tot&DA=SBC&q=%EB%AdropnaB%98%90'

# HTTP 요청을 통해 웹 페이지 가져오기
response = requests.get(url)

# 웹 페이지 파싱
soup = BeautifulSoup(response.text, 'html.parser')

# 로또 횟차 정보가 포함된 태그 찾기 (예시: <span class="txt_issue">제958회</span>)
lotto_round = soup.find('span', {'class': 'f_red'})

# 로또 횟차 출력
print(lotto_round.text if lotto_round else '로또 횟차 정보를 찾을 수 없습니다.')

1115회